### ISSUE TITLE
Having a set of logical variables Y, is it possible to constraint them all to be equal?

### ISSUE THREAD

**Issue by schlichtanders** [hdavid16/DisjunctiveProgramming.jl#107]
I know that one can do `@constraint(m, Y[1] == Y[2] == ... == Y[n] := true)`, but I am wondering whether this is also possible without explicitly naming all single Y.

**Comment by hdavid16** [comment]
Yes. It is possible with `@constraint(m, [i in 1:n], Y[i] := true)`

**Comment by pulsipher** [comment]
You can just use splatting with the `logical_and` function:
```julia
@constraint(m, logical_and(Y...) := true)
```
Other useful functions you can use include `logical_or`, `logical_not`, `implies`, and `iff`.

**Comment by schlichtanders** [comment]
reopened for tracking the documentation request

**Comment by hdavid16** [comment]
> You can just use splatting with the `logical_and` function:
> 
> ```julia
> @constraint(m, logical_and(Y...) := true)
> ```

@pulsipher , thank you for pointing out the splatting. The correct splatting based on @schlichtanders request would be:

```julia
> @constraint(m, iff(Y...) := true)
```

However, I will point out that neither of these are correct if you want to "constraint them all to be equal". Here is why:
1) `Y[1] == Y[2] == Y[3]` := true means that `Y[1] == Y[2] == Y[3]` must be true, which can be accomplished with and odd number of `true` values: e.g., `Y[1] = true`, `Y[2] = false`, and `Y[3] = false`.
2) `Y[1] and Y[2] and Y[3]` := true forces all of them to be true, but ignores the possibility of "all of them to be equal to false"

Therefore, only `@constraint(m, [i in 1:n-1], Y[i] == Y[i+1] := true)` will accomplish the "all equal" requirement by linking the variables sequentially. In the 3 variable example, this would be equivalent to `Y[1] == Y[2] := true` and `Y[2] == Y[3] := true'. These two constraints can only be satisfied if all of the variables are `true` or if all of them are `false`, meaning they are "all equal".

**Comment by pulsipher** [comment]
@hdavid16 To make them all equal (either true or false) with one constraint, couldn't you do the following:
```julia
@constraint(m, logical_and(Y...) || ¬logical_and(Y...) := true)
```
Which forces the variables to all be `true` or all be `false`. I suppose this doubles the number of terms in the constraint, but it should work.

**Comment by hdavid16** [comment]
@pulsipher yes that is another valid approach. However, you would need to have the negation inside the second `logical_and` so that you have that all are `false`:

```julia
@constraint(m, logical_and(Y...) || logical_and(logical_not.(Y)...) := true)
```

I suspect my sequential 2 term constraint set is more efficient, but I agree that it's great that the flexibility is there to test alternate representations.
