### ISSUE TITLE
support interval arithmetic for quadratic expressions

### ISSUE THREAD

**Issue by hdavid16** [hdavid16/DisjunctiveProgramming.jl#65]
need an analytical expression to find the min/max of the quadratic

**Comment by hdavid16** [comment]
Options:
- [ ] use `IntervalArithmetic.jl` to get a lower and upper bound on the min/max of a quadratic.
- [ ] use `IntervalOptimisation.jl` to get the min/max of a quadratic
- [ ] use `JuMP.jl` to solve the min/max problem
- [ ] an analytical approach?

**Comment by pulsipher** [comment]
Pyomo now avoids CNF altogether by default and instead uses a combination of algebraic and disjunctive constraints, taking inspiration from factorable programming: https://github.com/Pyomo/pyomo/blob/main/pyomo/contrib/cp/transform/logical_to_disjunctive_program.py

This is will yield a different MILP formulation, but the reformulation should be faster.

**Comment by hdavid16** [comment]
CNF is for the logic proposition constraints, not for Big-M, which is what this issue is about...
However, I'll have to take a look at what they do in that regard. Thanks!

**Comment by pulsipher** [comment]
Whoops, I posted on the wrong issue by mistake.

**Comment by hdavid16** [comment]
There is no analytical expression for a constrained quadratic that I know of. Getting tight Big-M values for quadratic or other nonlinear constraints will require solving a separate optimization problem...or borrowing something from PYOMO GDP.

**Comment by pulsipher** [comment]
I wonder how they "infer" "finite expression bounds" on nonlinear constraints.
