### ISSUE TITLE
Need to delete NLconstraint after reformulating its respective perspective function when using CHR

### ISSUE THREAD

**Issue by hdavid16** [hdavid16/DisjunctiveProgramming.jl#7]
This will require rebuilding the model or waiting until delete of an NLconstraint is supported: see https://github.com/jump-dev/JuMP.jl/issues/2355

**Comment by odow** [comment]
This will require rebuilding the model. We have no immediate plans to implement deletion of nonlinear constraints.

**Comment by hdavid16** [comment]
Yeah... that's what we'll have to do for now.
