### ISSUE TITLE
Have `@disjunction` automatically add exactly one constraints with a keyword argument

### ISSUE THREAD

**Issue by pulsipher** [hdavid16/DisjunctiveProgramming.jl#72]
Since 99% of the time this is the case, automating it would be nice. I think we should make it opt-in (i.e., the default would be `false`). 

One other thing to consider is whether the reformulations are still valid if this constraint is not given.

**Comment by hdavid16** [comment]
I think we should force this on the @disjunction call. It wasn't there before because we couldn't distinguish Nested from non nested disjunctions. Now that we can, we can add the appropriate Exactly constraint.

**Comment by pulsipher** [comment]
Ok, so you want something like `@disjunction(model, name_expr, lvars, exactly1 = true)` (i.e., the default is true)?

**Comment by hdavid16** [comment]
I think we should add it and not give the user the option of not adding it.

**Comment by pulsipher** [comment]
One thing to consider is under the new formal definition of GDP it seems like we are decoupling the exactly one constraint from the disjunction, so there might be cases where an exactly one constraint is not given. So, would it not better to give the user an option to not add it and then have reformulations error that rely on this assumption?

**Comment by hdavid16** [comment]
This recent paper always includes the exactly constraint as part of the extended GDP notation: https://arxiv.org/pdf/2303.04375.pdf.

**Comment by pulsipher** [comment]
Right and this paper also explicitly uses an exactly one constraint: https://www.sciencedirect.com/science/article/pii/S009813542300217X. The question is whether GDP requires there to always be an exactly one constraint. For instance, would it be possible to enforce exactly 2 out of 3 disjuncts?

**Comment by hdavid16** [comment]
Not unless there were some vagos reformulation, which is currently not the case

**Comment by pulsipher** [comment]
Thanks for the input @bernalde.

After talking with @hdavid16 offline, the game plan is as follows:
- add `exactly1 = true` keyword argument to `disjunction` (then `@disjunction` inherits it)
- modify `Disjunction` to store whether an exactly 1 constraint was added automatically
- have reformulation methods (e.g., hull) error if `exactly1= false` unless this is overridden via a keyword argument, thus, users have a way to manually add exactly 1 constraints if wanted, but will not accidently use reformulation techniques that depend on this assumption.
